### ISSUE TITLE
The function "Gestalt()" is deprecated on 10.8

### ISSUE THREAD

**Issue by jwilling** [github/twui#101]
The use of `Gestalt()` was introduced in commit 2fe383482357f to see if we're running on Lion or above. As of 10.8, this function is deprecated.

`sysctl(3)` should be used instead, perhaps.

**Comment by avaidyam** [comment]
`sysctl(3)` is a LOT harder than Gestalt() to check for, but sure. I'll patch that in.

**Comment by avaidyam** [comment]
Actually, I haven't found a way to use `sysctl` yet. Has anyone a hint for me? :D

**Comment by avaidyam** [comment]
```
#include <errno.h>
#include <sys/sysctl.h>

char str[256];
size_t size = sizeof(str);
int ret = sysctlbyname("kern.osrelease", str, &size, NULL, 0);
```

Is the closest I can get-- but Darwin release numbers MAY or MAY NOT correspond to OS X.

**Comment by jwilling** [comment]
I believe the kernel number for Lion was 11, if I'm not mistaken. Anything above that should be safe to use the Lion+ classes on.

**Comment by avaidyam** [comment]
We could also use `NSAppKitVersionNumber` which might be a cleaner way.

**Comment by jspahrsummers** [comment]
`NSAppKitVersionNumber` wasn't bumped from 10.7.4 to 10.8.0 (I believe), so it may not be entirely reliable.

**Comment by avaidyam** [comment]
Alright, then I'll open a PR for `sysctl(3)` tomorrow.
