### ISSUE TITLE
TUITextRenderer antialiasing

### ISSUE THREAD

**Issue by avaidyam** [github/twui#103]
For some reason, text rendered on my MacBook Pro's screen looks quite "thin" and "weak", whereas on my LED display, it looks normal, in line with the rest of Mac OS X. I believe this is an issue with `CGContextSetShouldSmoothFonts` being turned on, where a `CALayer` doesn't have sufficient `RGBA` information about the text's background to draw it "smoothly". Is there a way to fix this?

**Comment by jspahrsummers** [comment]
The background needs to be opaque for subpixel antialiasing to work correctly. This is very well-known and very well-documented issue on the web – we don't need to recap it here.

**Comment by avaidyam** [comment]
Is there an option to turn it off in `TUITextRenderer`?
