### ISSUE TITLE
NSView inside TUIScrollView overlaps the scroll view konb

### ISSUE THREAD

**Issue by luosheng** [github/twui#104]
I embedded a NSImageVIew in TUIScrollView in order to display animated GIFs, however the NSImageView overlaps the scroll view knob.

I think it's due to the implementation that NSViews (TUIViewNSViewContainer) must be on top of its sibling TUIViews. Of course I can switch to the traditional 'NS' way (by using a NSScrollView) in my case. I'm just wondering if there's other way around, or can we get rid of the NSView hierarchy limitation somehow?

**Comment by jspahrsummers** [comment]
Sorry, but this is one of the major limitations imposed by the AppKit bridging, and there's no real way around it while maintaining the same functionality. I would explore alternatives, like `NSScrollView` (as you mentioned).

**Comment by avaidyam** [comment]
Would it be a wise idea to list these as limitations in the `README`? And could you provide an image so I know what this is? If it is what I think it is, I might be able to help.

**Comment by jspahrsummers** [comment]
@galaxas0 They're listed in the `TUIViewNSViewContainer` documentation, as it should be.

**Comment by avaidyam** [comment]
@jspahrsummers Oh, thank you!
