### ISSUE TITLE
TUIImageRenderer?

### ISSUE THREAD

**Issue by avaidyam** [github/twui#111]
Much like `TUITextRenderer` which deals solely with the rendering of text onto a `CALayer`, why not offload the `tui_` methods on `NSImage` to a `TUIImageRenderer` object which, when told to draw, draws onto a layer with the chain of effects blocks?

The `ExampleTabBar` tabs are drawn by following a chain of image processing methods on `NSImage`. 

The benefits include exporting these methods into another class, leaving `NSImage` with less burden in case of OS API updates (No more `tui_` prefixing!), and more.

NOTE: I don't mean we need to add more features; just put less and less responsibility on AppKit.

**Comment by jwilling** [comment]
Actually, the extensions in the `NSImage` category mostly use CG functions (not related to AppKit), so the API will not be changing at all in the foreseeable future.

In terms of moving the functions elsewhere, I personally would disagree. I find the functions useful in my app for drawing a texture through code, then caching it for later (quick) use. Assuming the API user will only use it to draw into a layer is rather presumptuous, and I think it diminishes the utility of the methods. Additionally, even the fact that they return a `NSImage` leads to the natural association with a `NSImage` category.

This is rather open-ended and I don't want to speak for everyone. :wink2:

**Comment by avaidyam** [comment]
@jwilling I'm just going along with @jspahrsummers 's move to increase dependency on AppKit, but I feel like the image methods (even if they use CG functions) don't belong there. They're like sore sticklers that want a new home. In their defense, I think it's _because_ they're CG function based, they _don't_ need to be an `NSImage` category.

This new image renderer would function much like `TUITextRenderer`, is all I'd say. It doesn't _have_ to be layer-limited, too.  

## 

Aditya.

**Comment by jspahrsummers** [comment]
This seems wholly unnecessary to me. It's not at all clear what problem this would solve, or why we need to put less responsibility on AppKit.

**Comment by avaidyam** [comment]
Alright then, I'll close the issue.
