### ISSUE TITLE
TUITableViewCell Gradients

### ISSUE THREAD

**Issue by avaidyam** [github/twui#112]
Many UIKit and AppKit controls (such as the source list, or table view) have gradient drawing built in as part of their API. However, TwUI does not. I strongly urge for gradient support in `TUITableViewCell` as a complement to a source list component I'm working on. It's not the 1% case-- it's more like the 60% case that wants gradients. Even providing a non-API feature such as a gradient drawing block would be beneficial with little impact.

**Comment by jspahrsummers** [comment]
We already discussed this. I meant you should open an issue to talk about source lists, not revisit the conversation we already had.

`NSTableView` and `NSOutlineView` have a built-in gradient appearance, but they don't offer plug-n-play drawing of other gradients, and I think that's the right decision.
