### ISSUE TITLE
TUITableView doesn't move section headers when moving

### ISSUE THREAD

**Issue by maxgoedjen** [github/twui#113]
Regular cells seem to move fine, but they move under the section headers which remain static. Behavior can be seen in the sample project.

**Comment by maxgoedjen** [comment]
I believe that _layoutSectionHeaders: is immediately resetting the frame of the section header.

**Comment by avaidyam** [comment]
Could you describe this behavior with an image? I think this is how they're designed to work- section headers float above the cells when they're in the plain table view style.

**Comment by maxgoedjen** [comment]
[Here you go](http://f.cl.ly/items/443T2f3s3L2I0s3Y401G/photo.JPG)
Dragging cell #2 from section 1 to section 0 pushes cell #24 in section 0 to be under the section one header. (you can see the text box from cell 24, even if you can't see the text).
This bug is (partially) fixed in pull request [114](https://github.com/github/twui/pull/114). I haven't had enough time to look into it much deeper, I'm afraid.

**Comment by avaidyam** [comment]
Oh! Thank you, this makes much more sense. I'll see if I can look into it soon.
