### ISSUE TITLE
TUIDrawer....?

### ISSUE THREAD

**Issue by avaidyam** [github/twui#118]
Yes, I know that `NSDrawers` have long since been considered the bane of AppKit's existence (along with `NSCell`), but, as with `TUIPopover`, a TwUI-based customizable `NSPopover`, would it be possible to create something like a `TUIDrawer`? It would be fairly similar, aside from a few design pattern differences.

**Comment by jwilling** [comment]
What's wrong with `NSDrawer`? As far as I know, `TUIPopover` was created to solve a backwards compatibility issue, and not just for the sake of having a TwUI counterpart.

**Comment by avaidyam** [comment]
The `NSDrawer` is not very customizable and doesn't host `TUIView` background views (like the content view of an `NSWindow`). Another reason I believe `TUIPopover` was made to address was the customizability of the popover view.

**Comment by avaidyam** [comment]
I should also mention that, like `TUIPopover` (after my PR), this means that windows will be GPU-accelerated, with a `CALayer`-backed `TUIView` content view. That's my incentive here.

**Comment by jwilling** [comment]
A `NSWindow` itself cannot be "GPU-accelerated", so I'm not sure what you mean. You can get layers in a NSDrawer as well by simply telling the content view that you want a layer.

**Comment by avaidyam** [comment]
Hmm, that's a valid point. I guess it'd be better to use a `TUINSView` content view and tell its superview to use a layer.

**Comment by jspahrsummers** [comment]
Drawers are also recommended against by the HIG. They're a pretty archaic UI element.
