### ISSUE TITLE
TUINSWindow

### ISSUE THREAD

**Issue by avaidyam** [github/twui#119]
To what respect are we to flesh out `TUINSWindow`? I do recall @joshaber saying it would be a welcome addition, but as long as it wasn't extravagant.

**Comment by CodaFi** [comment]
Sorry about that accidental closing there, mate.  What were you thinking would make a window any better than it already is?  They seem to have reached their evolutionary apex.

**Comment by avaidyam** [comment]
@CodaFi LOL, I actually believe otherwise. (If only windows ran on `CALayers`!)
- Windows backed by `TUIView` content views, which allows for robust animations (somewhat).
- Custom window drawing made easier (Automatic, since `TUIView` has `drawRect`).
- No more need for `TUINSView` hosting would be quite nice. This would be the final stop in making TwUI, what I think, is a self-sufficient framework, hopefully, wholly not reliant on AppKit... I think.

**Comment by CodaFi** [comment]
There would still need to be a TUINSView host in the window, seeing as there's no way to outright replace NSWindow (at least not without some majorly annoying hacking), but I get your point.

**Comment by avaidyam** [comment]
Yeah, more or less! :) Just the bare minimum, hopefully. With titlebar heights…. :3

**Comment by CodaFi** [comment]
Perhaps you wouldn't even necessarily need to replace the contentView of the window, you could do what TUIPopover does and demand a contentView class object which must descend from NSView for initialization.

**Comment by avaidyam** [comment]
But `TUIPopover` uses `TUIPopoverBackgroundView` which is a `TUIView`….

**Comment by jwilling** [comment]
I do not understand the point of this.

A `NSWindow` will always have exactly one `contentView`, and it must always be a `NSView` or a subclass of `NSView`. You cannot "back" a window with a `TUIView`. The only benefit this wrapper would provide would be a couple lines of code to set up a `TUINSView` and set it as the content view of the window.

This needlessly hides implementation details, and I do not think it's needed.

**Comment by avaidyam** [comment]
Then, would it be better to remove it altogether?

**Comment by jwilling** [comment]
I find that `TUINSWindow` is an overly specific class, mainly created for Twitter for Mac. For one thing, the category on `NSWindow` for the first responder methods should probably be extracted into their own files.

I'll leave the deletion for `TUINSWindow` up to @joshaber.

**Comment by jwilling** [comment]
Closing this out as removing or modifying `TUINSWindow` at this point would be too major of a change.
