### ISSUE TITLE
TwUI Text Engine Updates

### ISSUE THREAD

**Issue by avaidyam** [github/twui#120]
I'm proposing to radically modify the underlying text engine that TwUI's text-based controls work on:

In progress:
- Add `TUITextDetector` which can parse a `TUITextStorage` instance for "action-able" information, such as emails, dates, times, twitter usernames, hashtags, people, addresses, and so on. It would then contain an action for the data type, perhaps a delegate method call or a block.
- Add `NSTextView` and `NSText` abilities to `TUITextView`.

Completed:
- Convert `TUIAttributedString` into `TUITextStorage`, which, quite self explanatorily, will be a storage class for text, and its modifiers (font, size, alignment, style, line break, etc,).
- Refactor `TUITextRenderer` slightly, into a class that renders a `TUITextStorage` and execute `TUITextDetector` actions.
- Rebuild `TUITextView` to become a subclass of `TUIScrollView`, like iOS, and hold an internal `TUITextRenderer`, abstracting these features into a superficial API that can be easily used.
- Rebuild `TUITextField` to remove dependency on `TUITextView` and hold an internal `TUITextRenderer`, and again, abstract these features into a superficial API.
- Leverage `TUILabel` and `TUITextField`, but leave editing ability only to `TUITextField`.

Are there any suggestions/complaints/comments on these proposed changes?

**Comment by avaidyam** [comment]
@jwilling Could you take a look at this? :)

**Comment by CodaFi** [comment]
I'm OK with the iOS-ification of the TUIText... components (seeing as they should scroll beautifully with that CVDisplayLink), but everything else is either overkill, or simply redundant (TUIAttributedString is already TUITextStorage sans some weird AppKit methods)

**Comment by avaidyam** [comment]
@CodaFi Actually, those features exist already. (`TUIDataDetector` is simply a delegate method with `ABActiveTextRange`/`Flavor` used together...) I just wanted to make them more obvious and easy to use.

**Comment by CodaFi** [comment]
Then I would say that Pull Requests speak louder than words.

**Comment by avaidyam** [comment]
But what if a PR is scrapped aside? ;) It's never a happy feeling to work on something and then have it shot down, so I decided to do things in the reverse this time.

**Comment by CodaFi** [comment]
Well, why not just do what we've been nagging you about for weeks and make a repository of all the ideas you have.  Trust me, we don't shoot you down because it's fun or it's some kind of sport, we do it because it's outside the scope of the framework. I mean, I could benefit from about 90% of the controls you suggest adding, but they're just too localized to be used in a general UI framework.

**Comment by avaidyam** [comment]
…. I think I'll do that this week then … Thanks!

**Comment by jwilling** [comment]
`TUITextField` definitely leaves a lot to be desired. It's buggy and is not customizable. I'll have to consider the others, but at least `TUITextField`, possibly even `TUITextView` and `TUILabel` are needing some attention.

**Comment by avaidyam** [comment]
I've begun work on this update here: https://github.com/galaxas0/twui/tree/upstream-text-engine
In case anyone wanted to follow/help.... please do! :smile:

**Comment by avaidyam** [comment]
I've completely refactored the internal architecture of `TUILabel`, `TUITextField`, `TUITextView`, and `TUIAttributedString` (now `TUITextStorage`). Aside from `TUITextView` not being a `TUIScrollView` subclass, or having proper API parity, this should be a good estimate of how the text control classes will look. The internal end of the engine, however, has not yet been revamped.

**Comment by jwilling** [comment]
If you're still going to share a lot of code between `TUITextField` and `TUITextView` (as it appears you are), you shouldn't duplicate it between the two. Try to find some way to share the duplicated code.

**Comment by avaidyam** [comment]
@jwilling I'm actually not. For now, this prevents the whole text view from breaking, but I plan to rewrite it as a proper subclass of `TUIScrollView`.

**Comment by avaidyam** [comment]
@CodaFi @jwilling Most of the tasks have been completed - there are still many `TUITextView` bugs, and the `TUITextField` scrolling bug to fix, however.

**Comment by CodaFi** [comment]
@galaxas0 I await your pull request, sir.

**Comment by avaidyam** [comment]
Alright!
