### ISSUE TITLE
TUIControl tabbing and focus rings

### ISSUE THREAD

**Issue by avaidyam** [github/twui#135]
- When using AppKit, tab and shift-tab allow you to navigate the responder chain for controls, but this doesn't happen on TUIKit.
- Focus rings are nonexistant on TUIKit, and I think we need them to actually indicate the focused element.

**Comment by jwilling** [comment]
Just drew my own focus rings last night. (This is a NSTextField though)

![](http://i.imgur.com/J1mgt.png)

Definitely not hard. Just use a combination of layer shadows and a custom fill and it looks perfect.

**Comment by avaidyam** [comment]
Mind providing a wee bit of sample code? ^_^ I'm revamping the TwUI text engine right now.

**Comment by jwilling** [comment]
Lets see how the class is designed first, then I'll know which drawing code you'll need.

**Comment by avaidyam** [comment]
Alright, sure! Thanks for helping :+1:

**Comment by avaidyam** [comment]
@jwilling :mailbox_with_mail: Do check the other PR for information, I've done a few changes to this.
