### ISSUE TITLE
Default initializers do not call standard initializers

### ISSUE THREAD

**Issue by CodaFi** [github/twui#137]
Scattered throughout the framework are controls which have the propensity to not initialize themselves completely if, say, `-init` is called over `-initWithFrame:`. Controls that exhibit this behavior often do not show themselves (such as TUIButton) in the view because they forget to initialize their subcomponents.  I propose a change to the coding conventions, in that setup work that does not involve the parameter(s) requested by the default initializer be done in `-init` or `-commonInit` so that all initializers in the framework create valid, and complete versions of themselves.

**Comment by avaidyam** [comment]
@CodaFi I've noticed this as well, having switched back to the github's TwUI fork from my private fork. I can try to fix this in my catalog example PR.
