### ISSUE TITLE
Remote view rendering

### ISSUE THREAD

**Issue by avaidyam** [github/twui#146]
Much like how iOS has the hidden `UIRemoteView` and `UIRemoteViewController`, I've been doing some research into remote rendering. Perhaps this would be a beneficial addition to TwUI for a few reasons: Mac App Store requires XPC/"separation of powers", and having remotely rendered views means it's much more safe to isolate components of your application (such as a status bar from the main application window, from an aux window of some sort), and the `MFMailComposeViewController` in iOS 6 already employs this well.

So far, what I've determined is the hierarchy should be as follows:
- Control order: `TUIRemoteViewController` --> `TUIRemoteView` --> `TUIRemoteLayer`.
- The `TUIRemoteLayer` should use a custom `CARenderer` to draw into an `IOSurface`.
- The `IOSurface` should be shared through mach ports between the two processes.
- The client `TUIRemoteLayer` should somehow (?) draw the `IOSurface`'s texture on itself.
- The client `TUIRemoteView` should pass all events through mach ports to the other `TUIRemoteView`.

This way, remote view rendering and event handling is possible. Any thoughts?

EDIT: So far, I've got an OpenGL demo working with a pretty slick API. Time to figure out how to get `CALayer` and `CARenderer` in there.

**Comment by jwilling** [comment]
What makes you think that the MAS "requires" XPC?

**Comment by avaidyam** [comment]
Oops, I forgot to specify the context-- my application has plugins through `NSBundle` loading, which definitely won't be allowed. I've handed over a `TUIView` that can maintain plugin state and acts as a drawing board for the loaded plugin. That's why I was interested in this endeavor. I have no issues implementing it (I'll be doing it either way), but if I were to build it around `TUIView`, and PR for it, only to have it shot down, it would be quite difficult to maintain on its own.

**Comment by jwilling** [comment]
Closing this as it is outside the scope of TwUI, and not applicable to the repo's current maintenance state.

**Comment by avaidyam** [comment]
:+1: Makes sense enough!
