### ISSUE TITLE
Contributions?

### ISSUE THREAD

**Issue by iluuu1994** [github/twui#157]
I will use TwUI in a private project.

I noticed that the performance many `TUIControl`s like `TUIImageView` could be greatly improved by using `CALayer.contents` instead of `drawRect:`.
No idea why at that time people decided to use `drawRect:`. The whole idea of this project is to render on the GPU rather than the CPU.

Ironically, this causes many apps that were built with TwUI to have very low frame rates, especially when resizing, since many of the views are completely redrawn. Try resizing the window of Wunderlist or Kickoff, terrible.

I know this fork is feature-frozen. 
Should I create a pull-request when I'm done or just keep it to myself?

**Comment by jwilling** [comment]
Thanks for your interest in contributing!

Only critical bug fixes are merged into this fork, not features or enhancements that could possibly break existing apps. So I'd suggest maintaining your own fork.

**Comment by iluuu1994** [comment]
Ok :/
