### ISSUE TITLE
TUIViewNSViewContainers aren't affected by transforms

### ISSUE THREAD

**Issue by jwilling** [github/twui#38]
When you have a TUIView with a TUIViewNSViewContainer added to it, transforms and animations applied to the TUIView's layer aren't applied to the TUIViewNSViewContainer. This might be impossible to fix.

**Comment by jspahrsummers** [comment]
There's code in there to handle animations, and `convertRect:toLayer:` is used for geometry, which should take transforms into account. Can you provide more information or some sample code?

**Comment by jspahrsummers** [comment]
After thinking about this some more, you're definitely right that an `NSView` won't appear transformed (though its coordinates should be correct). It is possible to fix, but the consequence might be loss of interactivity in the view.

Still, animations should work.

**Comment by jwilling** [comment]
Odd. Do animations only work when using `TUIView`'s block animation methods? Because when I use Core Animation to directly affect the layer's transform of a `TUIView`, a `NSView` contained inside it was not affected by the applied transform.

**Comment by jspahrsummers** [comment]
After investigating:
1. Animations do indeed only work when using `TUIView` animation methods. Animations added to the layer hierarchy currently do not animate `NSViews` alongside. Arguably, this sort of limitation is exactly what the `TUIViewNSViewContainer` documentation refers to (though I would still like to fix it).
2. Animating `TUIView.transform` will correctly animate hosted `NSViews`.
3. Hosted `NSViews` currently do not support sitting in a transformed state.

See [my changes to the example app](https://github.com/github/twui/blob/nsview-transform-support/ExampleProject/ConcordeExample/ExampleScrollView.m#L56) on the [nsview-transform-support](https://github.com/github/twui/tree/nsview-transform-support) branch.

**Comment by jwilling** [comment]
Thank you for looking into this. I had already reworked my hierarchy to work around this issue, and therefore hadn't looked into the header comments as much as I should have.

**Comment by choco** [comment]
I'm not sure if it's related to this but I was just messing around with the example app and got the following behaviour 
http://cl.ly/ITZm Just make an NSTextField as first responder and if you scroll it will still show over other TUIView (i.e. Tabbar)

**Comment by jspahrsummers** [comment]
@cHoco Definitely unrelated. Did you turn off [ENABLE_NSVIEW_CLIPPING](https://github.com/github/twui/blob/master/lib/UIKit/TUINSView.m#L38), by chance?

**Comment by choco** [comment]
No it's enabled, I just cloned the repository, compiled the example app and noticed this.

**Comment by jspahrsummers** [comment]
@cHoco Opened #41 to track that. Thanks for the heads-up.
