### ISSUE TITLE
NSImage and @2x

### ISSUE THREAD

**Issue by jwilling** [github/twui#39]
It seems that with the recent killing of `TUIImage` that we're back to square one in regards to @2x support again. If you have a HiDPi display, you can easily see that the example project does not draw in high resolution, even though @2x assets are provided.

**Comment by jspahrsummers** [comment]
This is almost certainly an issue with the demo app specifically, like (perhaps) not passing a context to `CGImageForProposedRect:context:hints:`. @2x support should be even easier and better supported with `NSImage` than with `TUIImage`.

**Comment by jwilling** [comment]
Then perhaps the demo app should be updated to reflect this and accurately demonstrate HiDPi support.

**Comment by jspahrsummers** [comment]
Certainly, just adding notes for posterity.

**Comment by jspahrsummers** [comment]
Fixed by pull request #40.

**Comment by jwilling** [comment]
:thumbsup:

**Comment by jwilling** [comment]
@jspahrsummers Hmm, noticed another odd thing. Not sure if this is a retina-only bug, or not. Try playing around with `tui_innerShadowWithOffset`. It really doesn't do what it's supposed to do, at least on my retina display. If the blur radius is increased, it shrinks the rendered shadow but doesn't increase the blur radius as expected.

**Comment by jspahrsummers** [comment]
@jwilling I honestly don't like those methods at all. Nothing against image manipulation, by any means, but they're very specific (very obviously added just for Twitter for Mac) and don't really have anything to do with TwUI's larger purpose.

I ported them over to `NSImage` because they were already there and I figured they're not even worth removing, but I don't think it's a great use of time to maintain such purpose-specific drawing code. I'd be happy to review any pull requests dealing with them, though. :)

**Comment by jwilling** [comment]
@jspahrsummers Okay, I'll look into it. :smile:

**Comment by avaidyam** [comment]
Quite honestly, why not leave the TUIImage class alone? Why not have TwUI stay a lightweight AppKit replacement, replicating each class, and instead going for CoreAnimation usage?

**Comment by jwilling** [comment]
@galaxas0 Because as OS X progresses forward, it is better to automatically be able to use the newest and latest goodies in each OS X release without having to worry about updating for compatibility.

**Comment by avaidyam** [comment]
Ah, the goodies. Alright then, that makes sense. I was actually using TwUI in a really, really customized way, tailored to avoid AppKit in my app, but I guess this works. But we still need a solid text editing foundation, are we going to commit to that in TwUI?

**Comment by jspahrsummers** [comment]
@galaxas0 I don't understand your question about text editing. Do you mind opening a new issue for discussion?

**Comment by avaidyam** [comment]
Sure!
