### ISSUE TITLE
NSTextField first responder does not properly clip

### ISSUE THREAD

**Issue by jspahrsummers** [github/twui#41]
From @cHoco (in #38):

> I'm not sure if it's related to this but I was just messing around with the example app and got the following behaviour 
> http://cl.ly/ITZm Just make an NSTextField as first responder and if you scroll it will still show over other TUIView (i.e. Tabbar)

**Comment by choco** [comment]
I also forgot to add that the tableview gets stuck when I do this. A video explains it better, http://cl.ly/ITM5
