### ISSUE TITLE
NSTextField hosted in a TUITableViewCell - Text flips during certain animations

### ISSUE THREAD

**Issue by gcox** [github/twui#48]
This can be seen in the example project:

Steps to reproduce:
- Run the example
- Enter some text in one of the NSTextFields in the table view
- Drag the row below it upward
- The text entered in the NSTextField flips upside down until the re-order animation completes

It can be difficult to see since the problem row slides behind the row being dragged.  It's easier to see if the test you enter is something like "AAAAAAAA", pretty obvious when that flips upside down.

**Comment by jspahrsummers** [comment]
Are you on the latest master? This should've been fixed by 574340d57db39a2e7f9939d03ef03108f215a953.

**Comment by gcox** [comment]
Yes, I'm on the lastest master.  Did the repro steps not work for you?

**Comment by jspahrsummers** [comment]
Sorry, I hadn't tried to reproduce it yet when I wrote that comment (just wanted to nip it in the bud if it was something simple).

Thanks for reporting this! Pull request #49 should fix it.

**Comment by jspahrsummers** [comment]
Super really hardcore fixed by #65.
