### ISSUE TITLE
TUIPopover transparent background

### ISSUE THREAD

**Issue by avaidyam** [github/twui#55]
I can't figure out for the life of me how to have a transparent background (like MAAttachedWindow) using a TUIPopover background view class. It just doesn't work. I ended up rewriting the class to make that work, but it should be possible without a rewrite. What am I doing wrong!??!

**Comment by dannygreg** [comment]
You don't need a re-write the default appearance has a transparent background, simply giving it a different `drawRect` block should be enough.

**Comment by avaidyam** [comment]
It shows up gray, instead of translucent black... that's what I was struggling with  :\

**Comment by dannygreg** [comment]
Oh this may have something to do with the window behind it. We rushed it out doing some of the drawing, the fix would be to move whatever is being drawn in the window to drawing in the view, which was the original design.

**Comment by avaidyam** [comment]
So what would I have to do to fix this? Just remove the underlying view? Because that removes the popover shadow along with it.

**Comment by dannygreg** [comment]
The fix is to move the drawing code in the window subclass to the backing view. That way it will get changed by any subclassing (as intended). There is even a comment to that effect in the code.

**Comment by avaidyam** [comment]
Closed on account of a PR being opened to fix this.
