### ISSUE TITLE
Any reason for the "tui_" or "ab_" in method names?

### ISSUE THREAD

**Issue by avaidyam** [github/twui#56]
Why do we need the "tui_" in front of the category method names? Seems like these would be methods only TwUI would use, and therefore do not require a "tui_" in front.

**Comment by jspahrsummers** [comment]
See Apple's [API Naming Guidelines](https://developer.apple.com/library/mac/documentation/MacOSX/Conceptual/BPFrameworks/Concepts/CreationGuidelines.html#//apple_ref/doc/uid/20002254-105643):

> If you are writing a category for an Objective-C class, you should also use some sort of unique prefix in your method names. Because categories can be loaded dynamically from multiple sources, a unique prefix helps ensure that the methods in your category don’t conflict with those in other categories.

**Comment by avaidyam** [comment]
Oh, I did not know that. Another question: are you open to categories that TwUI developers would use (such as NSBezierPath rounded corners)?

**Comment by jspahrsummers** [comment]
No, because there's no reason to put that in TwUI instead of elsewhere. Among other reasons, it doesn't use or interact with anything in TwUI already.

See the [Contributing](https://github.com/github/twui#contributing) section of the README.
