### ISSUE TITLE
TUIPopover

### ISSUE THREAD

**Issue by avaidyam** [github/twui#8]
I've modified the TUIPopover to near-perfectly (like, nearly indistinguishably) mimic the NSPopover, but this also removes the ability to set a custom style and custom TUIPopoverBackgroundView. Should I consider a pull request for it? The main reason I did this was for the shadow on the popover, along with the transparency. For some reason, both of them don't like each other.

**Comment by joshaber** [comment]
The answer to "should I open a pull request?" is always an emphatic yes!

**Comment by avaidyam** [comment]
But it's not at all API-compatible with the current one :[ It does however, look identical, and allow a hosted UXView.

**Comment by avaidyam** [comment]
Oh, and it's a lot less messy code-wise (no more inline blocks that made no sense, sorry :P)
