### ISSUE TITLE
TUIStyledView merge

### ISSUE THREAD

**Issue by avaidyam** [github/twui#80]
Would it not be better to merge TUIStyledView into TUIView? It's a _very_ think wrapper just for two properties.

**Comment by jwilling** [comment]
My vote is to remove it entirely. Seems like it's not reusable enough to warrant its place in the framework.

**Comment by avaidyam** [comment]
Which is why I wanted to merge it with TUIView- it's still there, but it's not a big "lego block" in the framework.

**Comment by jwilling** [comment]
No, actually I mean to remove all the code entirely. I see no reason to use this over setting `borderWidth` and `borderColor` on a standard TUIView's layer.

**Comment by avaidyam** [comment]
Oh, that's what I meant I wanted to do- expand the TUIView interface to directly manipulate the CALayer, which gives us these properties without manual drawing like this.

**Comment by jspahrsummers** [comment]
@galaxas0 What's the advantage to having those wrappers?

**Comment by avaidyam** [comment]
To be honest, not much- it's for compatibility reasons. Rather than calling `view.layer.something` you'd call `view.something`, and if my suspicions  are correct, @joshaber added `TUIStyledView` for simpler, custom drawing. Now, he can just switch `TUIStyledView` to `TUIView` and all will be well with the world. 

But that's all it is. I would agree with a complete removal of the class, but the _slight_ compatibility break with whoever is using it was what I was trying to address.

**Comment by jspahrsummers** [comment]
@galaxas0 Either way. Removing it would be simpler, but I guess it comes down to what PR is submitted first. :P

**Comment by avaidyam** [comment]
Sure, then, after my existing PRs are cleared, I've got a few more to push :P (Sorry I'm overdosing on PRs xD)

**Comment by jspahrsummers** [comment]
This should probably stay open until a PR addresses it, or unless we determine that we don't want to fix it.

**Comment by avaidyam** [comment]
Since I have made a PR that _does_ address this, I'll close this issue.

**Comment by jspahrsummers** [comment]
I should be clearer – an issue should stay open until a pull request that addresses it _is merged_.

**Comment by avaidyam** [comment]
Ah, alright then.
