### ISSUE TITLE
New component TUISplitView

### ISSUE THREAD

**Issue by choco** [github/twui#81]
Before starting to work on something similar, I wanted to gather some opinions and advices. 

Is this something that may find its way into the TwUI framework if correctly implemented? 
From a class design point of view, should we try to resemble the Apple implementation or others which come to your minds? 

I will develop it anyway since I need it for a personal project, because NSSplitView doesn't perform as well as I'd like. But  first I wanted to check if you guys were interested so I would try to build something solid, and not just a quick hack.

**Comment by jspahrsummers** [comment]
@jwilling has written [an NSSplitView replacement](https://github.com/jwilling/JWSplitView).

**Comment by jwilling** [comment]
Yes, but there is quite a bit more that needs to be done. I also wrote a hacky [TUISplitView](https://github.com/jwilling/TUISplitView), but it's quite broken.

You can also give [M3AppKit](https://github.com/pilky/m3appkit)'s split view a try. It seems to be fully functional, unlike mine.

**Comment by avaidyam** [comment]
And I've also been writing a split view too..... Just let me get my existing pull requests out the door and I'll add those too.

**Comment by jwilling** [comment]
To tell you the truth, I became disenchanted with writing a TwUI-only split view after I realized how impractical it would be in other projects. Personally I think writing a split view in AppKit (using constraints, for instance) will be far more future-proof, and much more worth your time.

**Comment by jspahrsummers** [comment]
I agree with @jwilling. If there's a good already-written TwUI-based split view, I think it makes sense to add, but it's probably not worth the effort as a new project. AppKit + TwUI bridging will work better.

**Comment by choco** [comment]
Ok, thank you guys for the feedback :) I'll take a look at @jwilling split view replacement and see how it goes!

## 

Enrico Ghirardi

Il giorno giovedì 20 settembre 2012, alle ore 20:19, Justin Spahr-Summers ha scritto:

**Comment by jwilling** [comment]
@cHoco You might want to look at @pilky's replacement first, as his seems to be more feature-complete and tested than mine. Mine just doesn't have many features and hasn't been tested throughly enough.
