### ISSUE TITLE
Code cleanup!

### ISSUE THREAD

**Issue by avaidyam** [github/twui#82]
As the code base of TwUI has expanded massively since the first release, I do think it's time for a clean up. A lot of methods are cluttered with nested statements and need to be factored, and there are a few event-lock-loops in there (`while(1) { doSomething(event); getNewEvent(); }`) that need to be safety proofed. Our documentation is also VERY lacking.

For now, this is a bulletin notice, as I'll begin to work on a few of these issues, but I certainly cannot do this alone. And someone has GOT to teach me to put Xcode in tabs-only mode. That bugger's driving me bonkers.

**Comment by CodaFi** [comment]
How do you propose we go about documenting the source?  What format (AppleDoc, Doxygen, Inline Comments etc.)?  Should having AppleDoc or Doxygen be a requirement, or should there be a separate target for the various docs and non-docs flavored versions?

**Comment by avaidyam** [comment]
Appledoc for sure on that, and we need a lot of inline comments on the implementation side to explain what the heck the code does. It doesn't have to be a requirement yet, but eventually it should be mandate. We don't need a separate target for that, since it's just fancy comments.
