### ISSUE TITLE
dequeueReusableCellWithIdentifier return cells in reverse order

### ISSUE THREAD

**Issue by matpaul** [github/twui#83]
I could be wrong, but it seems reusable cell mechanism work not quite correct.
For example - we create 4 cells in table, their addresses are:
     <CustomCell: 0x101ca6740>
     <CustomCell: 0x10026ac30>
     <CustomCell: 0x101cac380>
     <CustomCell: 0x10026f2d0>

After reloadData, dequeueReusableCellWithIdentifier returned:
     <CustomCell: 0x10026f2d0>
     <CustomCell: 0x101cac380>
     <CustomCell: 0x10026ac30>
     <CustomCell: 0x101ca6740>

**Comment by jspahrsummers** [comment]
You shouldn't be depending on the order of cells returned as reusable cells. They're intended to be skeleton objects available to reuse, not literal reuse with the same values.

See the `UITableView` iOS documentation for more information. The mechanism is exactly the same.

**Comment by matpaul** [comment]
Thanks

**Comment by avaidyam** [comment]
^ I had this issue a while ago too- just do as iOS does. Except a bit of Mac in the middle.
