### ISSUE TITLE
TUITableView reports it's contentOffset in the 10's of thousands

### ISSUE THREAD

**Issue by CodaFi** [github/twui#87]
`TUITableView` appears to be incorrectly calculating it's `-contentOffset` by multiplying the number of cells it has by their heights, then adding the size of its `-pullDownView` and negating the whole deal.  This appears to be a side effect of the Mac's coordinate system, but I have no idea where the negatives are coming from.

Sample logs from 

``` Objective-C
- (void)scrollViewDidScroll:(TUIScrollView *)scrollView{
    NSLog(@"%@", NSStringFromPoint(NSPointFromCGPoint(scrollView.contentOffset)));    
}

{0, -17597}
{0, -17596}
{0, -17594}
{0, -17593}
{0, -17593}
{0, -17592}
{0, -17591}
{0, -17590}

```

**Comment by jwilling** [comment]
`TUIKit` uses a bottom-left coordinate system, which is the same as in Core Animation and Core Graphics.

The property you're looking for is `pullOffset`.

**Comment by CodaFi** [comment]
But contentOffset on iOS isn't measured from bottom to top, and it most certainly isn't measured by multiplying the data set by it's heights.

**Comment by jwilling** [comment]
The coordinate system on iOS being different from CA has been a source of endless frustration for a lot of developers. It's better to unify with CA, having it bottom-left. That was one of the fundamental design decisions Loren made in TwUI.

**Comment by avaidyam** [comment]
I just ran into this issue-- check out my twui fork with the new `TUIRefreshControl` here: https://github.com/galaxas0/twui/tree/upstream-refresh-control
