### ISSUE TITLE
How to host raw CALayers inside TUIView?

### ISSUE THREAD

**Issue by NeomMob** [github/twui#92]
Hello,
This is not an issue (is there a better place to ask a question) but an HowTo request.
How to host plain CALayers (and animate them) inside a TUIView?

Thanks and regards,

**Comment by jspahrsummers** [comment]
You can add your own layers to the `layer` property of any `TUIView`. You retain full control over them, and must lay them out or animate them as you see fit.

The behavior is pretty similar to what's available on iOS, so most simple iOS examples will translate almost one-to-one.

**Comment by avaidyam** [comment]
There is no concept of layer-hosting or layer-backed in TwUI. You can, however, modify a view's `CALayer` class and add sublayers to it.
