### ISSUE TITLE
TUILayoutConstraint Additions

### ISSUE THREAD

**Issue by avaidyam** [github/twui#94]
At the moment, my implementation of `TUILayoutConstraint` only supports equality constraints (`==`). It would be nice if they supported inequalities (`>=`, `<=`, `>`, `<`), but alas, I have no idea how to go about this. Would anyone have an ideas on how to implement this?

There's also a few things I'd like to fix:
- A weird `superview` layout bug (requiring the superview to have a layout name).
- Removal of layout names: I'm thinking of using `-[NSProcessInfo globallyUniqueString]` instead.
- ASCII-art based layout construction - this one's a LOT harder.
- AppKit bridging for layouts. I have no idea how the current bridging architecture works though.

VFL (Autolayout language) is documented here: 
http://developer.apple.com/library/mac/#documentation/UserExperience/Conceptual/AutolayoutPG/Articles/formatLanguage.html#//apple_ref/doc/uid/TP40010853-CH3

**Comment by jspahrsummers** [comment]
Added the "enhancement" label and removed it from the issue title.

**Comment by avaidyam** [comment]
Could you tell me how to do that? It doesn't seem possible from github.com. :\

**Comment by jspahrsummers** [comment]
Apparently only collaborators can do it. Never realized that.

**Comment by avaidyam** [comment]
Hmm, alright!
