### ISSUE TITLE
NSColor CGColor property

### ISSUE THREAD

**Issue by avaidyam** [github/twui#95]
There's already a `CGColor` property on `NSColor`. Is there a reason we need to add a new `tui_CGColor` property?

**Comment by jspahrsummers** [comment]
`NSColor.CGColor` is only available on 10.8 and later.

**Comment by avaidyam** [comment]
And only moments after posting this issue, I figure out the answer. I'm sorry, I'll check the APIs next time too.

**Comment by avaidyam** [comment]
Wouldn't it be a good idea to rename `tui_CGColor` to simply `CGColor` and use

```
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wobjc-protocol-method-implementation"
// -CGColor and -setCGColor methods here.
#pragma clang diagnostic pop
```

to replace 10.8's default implementation? This would allow for easier cross-version programming and a more cohesive codebase.

EDIT: I've PR'd for this.
