### ISSUE TITLE
Removal of certain "tui" prefixed methods.

### ISSUE THREAD

**Issue by avaidyam** [github/twui#97]
A few `tui_` prefixed methods don't have to be prefixed, such as `tui_performWithDisabledActions`, `tui_CGImage`, `tui_fontWithName`, and a few more `NSImage` methods. These aren't necessarily private methods, they don't conflict with existing methods, and would be used fairly often in TwUI. Is there a reason they need to be prefixed?

**Comment by jspahrsummers** [comment]
The use of a prefix prevents methods from colliding now _or in the future_. It's a forward-compatible way to add methods without worrying about whether we're clobbering Apple's (public _or private_).

**Comment by avaidyam** [comment]
… there sure is a lot of clobbering going on here. Alright, that's fine then. I was just checking out which bits of the code might need work, is all.
